import { addDays, format } from 'date-fns';
import type { Trip, Day, Activity } from '@/types';

/**
 * Creates a sample Ha Long Bay 3 days 2 nights trip
 * Starting from tomorrow for demo purposes
 */
export function createSampleHaLongTrip(): Trip {
  const startDate = addDays(new Date(), 1);
  const tripId = 'sample-halong-trip';
  
  const day1Activities: Omit<Activity, 'dayId'>[] = [
    {
      id: 'a1-1',
      title: 'Xuất phát từ Hà Nội',
      timeStart: '06:00',
      timeEnd: '06:30',
      locationText: 'Điểm đón khách - Hà Nội',
      category: 'transport',
      costEstimate: 0,
      notes: 'Xe đón tại khách sạn hoặc điểm hẹn',
      orderIndex: 0,
    },
    {
      id: 'a1-2',
      title: 'Di chuyển Hà Nội - Hạ Long',
      timeStart: '06:30',
      timeEnd: '10:30',
      locationText: 'Cao tốc Hà Nội - Hạ Long',
      category: 'transport',
      costEstimate: 350000,
      notes: 'Xe limousine 9 chỗ, có wifi',
      orderIndex: 1,
    },
    {
      id: 'a1-3',
      title: 'Check-in du thuyền',
      timeStart: '11:00',
      timeEnd: '11:30',
      locationText: 'Cảng tàu quốc tế Tuần Châu',
      category: 'other',
      costEstimate: 0,
      orderIndex: 2,
    },
    {
      id: 'a1-4',
      title: 'Ăn trưa trên du thuyền',
      timeStart: '12:00',
      timeEnd: '13:30',
      locationText: 'Du thuyền Ambassador',
      category: 'food',
      costEstimate: 0,
      notes: 'Buffet hải sản tươi sống',
      orderIndex: 3,
    },
    {
      id: 'a1-5',
      title: 'Tham quan hang Sửng Sốt',
      timeStart: '14:00',
      timeEnd: '15:30',
      locationText: 'Hang Sửng Sốt, Vịnh Hạ Long',
      category: 'tickets',
      costEstimate: 200000,
      notes: 'Hang động đẹp nhất Vịnh Hạ Long',
      orderIndex: 4,
    },
    {
      id: 'a1-6',
      title: 'Chèo kayak khám phá',
      timeStart: '16:00',
      timeEnd: '17:30',
      locationText: 'Làng chài Vung Viêng',
      category: 'tickets',
      costEstimate: 150000,
      notes: 'Chèo kayak quanh làng chài, ngắm hoàng hôn',
      orderIndex: 5,
    },
    {
      id: 'a1-7',
      title: 'Ăn tối & tiệc BBQ',
      timeStart: '19:00',
      timeEnd: '21:00',
      locationText: 'Du thuyền Ambassador',
      category: 'food',
      costEstimate: 0,
      notes: 'BBQ hải sản trên boong tàu',
      orderIndex: 6,
    },
    {
      id: 'a1-8',
      title: 'Nghỉ đêm trên du thuyền',
      timeStart: '21:00',
      locationText: 'Du thuyền Ambassador - Vịnh Lan Hạ',
      category: 'stay',
      costEstimate: 2500000,
      notes: 'Phòng Deluxe view biển, 2 người/phòng',
      orderIndex: 7,
    },
  ];

  const day2Activities: Omit<Activity, 'dayId'>[] = [
    {
      id: 'a2-1',
      title: 'Tập Tai Chi buổi sáng',
      timeStart: '06:00',
      timeEnd: '06:45',
      locationText: 'Boong tàu',
      category: 'other',
      costEstimate: 0,
      notes: 'Ngắm bình minh trên vịnh',
      orderIndex: 0,
    },
    {
      id: 'a2-2',
      title: 'Ăn sáng buffet',
      timeStart: '07:00',
      timeEnd: '08:00',
      locationText: 'Du thuyền Ambassador',
      category: 'food',
      costEstimate: 0,
      orderIndex: 1,
    },
    {
      id: 'a2-3',
      title: 'Tham quan đảo Titop',
      timeStart: '08:30',
      timeEnd: '10:30',
      locationText: 'Đảo Titop, Vịnh Hạ Long',
      category: 'tickets',
      costEstimate: 100000,
      notes: 'Leo 400 bậc thang lên đỉnh, view toàn cảnh vịnh',
      orderIndex: 2,
    },
    {
      id: 'a2-4',
      title: 'Tắm biển đảo Titop',
      timeStart: '10:30',
      timeEnd: '11:30',
      locationText: 'Bãi biển Titop',
      category: 'other',
      costEstimate: 0,
      notes: 'Nước biển trong xanh, cát trắng mịn',
      orderIndex: 3,
    },
    {
      id: 'a2-5',
      title: 'Ăn trưa & trả phòng',
      timeStart: '12:00',
      timeEnd: '13:00',
      locationText: 'Du thuyền Ambassador',
      category: 'food',
      costEstimate: 0,
      orderIndex: 4,
    },
    {
      id: 'a2-6',
      title: 'Di chuyển về Tuần Châu',
      timeStart: '13:00',
      timeEnd: '14:00',
      locationText: 'Cảng Tuần Châu',
      category: 'transport',
      costEstimate: 0,
      orderIndex: 5,
    },
    {
      id: 'a2-7',
      title: 'Check-in khách sạn',
      timeStart: '14:30',
      timeEnd: '15:00',
      locationText: 'Vinpearl Resort Hạ Long',
      category: 'stay',
      costEstimate: 1800000,
      notes: 'Phòng Superior, view vịnh',
      orderIndex: 6,
    },
    {
      id: 'a2-8',
      title: 'Tự do khám phá Vinpearl',
      timeStart: '15:00',
      timeEnd: '18:00',
      locationText: 'Vinpearl Hạ Long',
      category: 'tickets',
      costEstimate: 500000,
      notes: 'Công viên nước, vườn thú, aquarium',
      orderIndex: 7,
    },
    {
      id: 'a2-9',
      title: 'Ăn tối hải sản',
      timeStart: '19:00',
      timeEnd: '21:00',
      locationText: 'Nhà hàng Cái Dăm',
      category: 'food',
      costEstimate: 800000,
      notes: 'Hải sản tươi sống, đặc sản địa phương',
      orderIndex: 8,
    },
  ];

  const day3Activities: Omit<Activity, 'dayId'>[] = [
    {
      id: 'a3-1',
      title: 'Ăn sáng tại khách sạn',
      timeStart: '07:00',
      timeEnd: '08:00',
      locationText: 'Vinpearl Resort',
      category: 'food',
      costEstimate: 0,
      orderIndex: 0,
    },
    {
      id: 'a3-2',
      title: 'Check-out khách sạn',
      timeStart: '10:00',
      timeEnd: '10:30',
      locationText: 'Vinpearl Resort',
      category: 'other',
      costEstimate: 0,
      orderIndex: 1,
    },
    {
      id: 'a3-3',
      title: 'Tham quan chợ đêm Hạ Long',
      timeStart: '10:30',
      timeEnd: '12:00',
      locationText: 'Chợ đêm Hạ Long',
      category: 'other',
      costEstimate: 200000,
      notes: 'Mua đặc sản, quà lưu niệm',
      orderIndex: 2,
    },
    {
      id: 'a3-4',
      title: 'Ăn trưa trước khi về',
      timeStart: '12:00',
      timeEnd: '13:00',
      locationText: 'Nhà hàng Phố Biển',
      category: 'food',
      costEstimate: 400000,
      notes: 'Bún chả mực, bánh cuốn chả mực',
      orderIndex: 3,
    },
    {
      id: 'a3-5',
      title: 'Di chuyển Hạ Long - Hà Nội',
      timeStart: '13:30',
      timeEnd: '17:00',
      locationText: 'Cao tốc Hạ Long - Hà Nội',
      category: 'transport',
      costEstimate: 350000,
      notes: 'Nghỉ ngơi trên xe, dừng 1 điểm giữa đường',
      orderIndex: 4,
    },
    {
      id: 'a3-6',
      title: 'Về đến Hà Nội',
      timeStart: '17:00',
      locationText: 'Hà Nội',
      category: 'transport',
      costEstimate: 0,
      notes: 'Kết thúc chuyến đi, hẹn gặp lại!',
      orderIndex: 5,
    },
  ];

  const days: Day[] = [
    {
      id: 'day-1',
      tripId,
      date: format(startDate, 'yyyy-MM-dd'),
      orderIndex: 0,
      activities: day1Activities.map((a) => ({ ...a, dayId: 'day-1' })),
    },
    {
      id: 'day-2',
      tripId,
      date: format(addDays(startDate, 1), 'yyyy-MM-dd'),
      orderIndex: 1,
      activities: day2Activities.map((a) => ({ ...a, dayId: 'day-2' })),
    },
    {
      id: 'day-3',
      tripId,
      date: format(addDays(startDate, 2), 'yyyy-MM-dd'),
      orderIndex: 2,
      activities: day3Activities.map((a) => ({ ...a, dayId: 'day-3' })),
    },
  ];

  const now = new Date().toISOString();

  return {
    id: tripId,
    title: 'Du lịch Hạ Long 3N2Đ',
    startDate: format(startDate, 'yyyy-MM-dd'),
    endDate: format(addDays(startDate, 2), 'yyyy-MM-dd'),
    timezone: 'Asia/Ho_Chi_Minh',
    currency: 'VND',
    numberOfPeople: 4,
    days,
    costSettings: { splitMode: 'equal' },
    createdAt: now,
    updatedAt: now,
  };
}
